import axios from "axios";

export const API_URL = "http://localhost:5000/api";

export const registerUser = async (email: string, password: string) => {
  try {
    const response = await axios.post(`${API_URL}/users/signup`, { email, password });
    console.log(response.data.response, "response from auth.ts upon registering a new user from client");
    const accessToken = response?.data?.response?.accessToken;
    const userEmail = response?.data?.response?.user?.email;
    const userId = response?.data?.response?.user?.id;

    return { accessToken, userEmail }; //this is the user + token object generated by the backend Signup controller handler
  } catch (error) {
    console.error("Error signing up", error);
    throw error;
  }
};

export const loginUser = async (password: string, email: string) => {
  try {
    const response = await axios.post(`${API_URL}/auth/login`, { password, email });
    const accessToken = response?.data?.response?.accessToken;
    const userEmail = response?.data?.response?.user?.email;
    const userId = response?.data?.response?.user?.id;

    return { accessToken, userEmail, userId }; //this is the user + token object generated by the backend login controller handler
  } catch (error) {
    console.error("Error signing up", error);
    throw error;
  }
};
